steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.','-t', 'ci/tags:$BRANCH_NAME-$BUILD_ID']
- name: 'gcr.io/$PROJECT_ID/cloud-builder'
  args: ['test_unit']
  env:  ['DOCKER_COMPOSE_FLAGS=-f docker-compose.ci.yml','BUILD_NUMBER=$BUILD_ID']

